M48
; DRILL file {KiCad 9.0.1} date 2025-04-14T14:12:29-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-14T14:12:29-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X98.98Y-43.64
X106.18Y-43.64
T2
X63.38Y-42.823
X63.38Y-117.823
X128.38Y-42.823
X128.38Y-117.823
M30
